### ISSUE TITLE
Deploy image static analysis github action workflow for security scanning

### ISSUE THREAD

**Issue by Pasarus** [interactivereduction/gitops#13]
Snyk: https://snyk.io/plans/ (Either only on PR, or on Main? concerns with main and the max limits on free)
Clair: https://quay.github.io/clair/whatis.html (Free)

More?

**Comment by keiranjprice101** [comment]
Closed in related PRs:
https://github.com/interactivereduction/jobcontroller/pull/146
https://github.com/interactivereduction/file-watcher/pull/111
https://github.com/interactivereduction/IR-API/pull/291
https://github.com/interactivereduction/run-detection/pull/244
